//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Marble Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MarbleControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MarbleControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Marble Controls"",
    ""maps"": [
        {
            ""name"": ""RotationControl"",
            ""id"": ""e444048b-b218-45d3-9245-a32950b63616"",
            ""actions"": [
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""b5b25a68-2b3e-458d-b6b4-6d10a06a3df8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d1577489-e8d9-4dc5-955f-017a44292f53"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8c52f02a-7550-4279-8e45-6c54705f0155"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard And Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b9ac959a-539a-45c1-8259-371f65a0e6e0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard And Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5c2e36b5-ee4f-4379-8622-ee83c7bc78de"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard And Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""909b764f-fc36-4723-a426-3616a34e75ee"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard And Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard And Mouse"",
            ""bindingGroup"": ""Keyboard And Mouse"",
            ""devices"": []
        },
        {
            ""name"": ""Gampad"",
            ""bindingGroup"": ""Gampad"",
            ""devices"": []
        }
    ]
}");
        // RotationControl
        m_RotationControl = asset.FindActionMap("RotationControl", throwIfNotFound: true);
        m_RotationControl_Rotate = m_RotationControl.FindAction("Rotate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RotationControl
    private readonly InputActionMap m_RotationControl;
    private IRotationControlActions m_RotationControlActionsCallbackInterface;
    private readonly InputAction m_RotationControl_Rotate;
    public struct RotationControlActions
    {
        private @MarbleControls m_Wrapper;
        public RotationControlActions(@MarbleControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Rotate => m_Wrapper.m_RotationControl_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_RotationControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RotationControlActions set) { return set.Get(); }
        public void SetCallbacks(IRotationControlActions instance)
        {
            if (m_Wrapper.m_RotationControlActionsCallbackInterface != null)
            {
                @Rotate.started -= m_Wrapper.m_RotationControlActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_RotationControlActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_RotationControlActionsCallbackInterface.OnRotate;
            }
            m_Wrapper.m_RotationControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
            }
        }
    }
    public RotationControlActions @RotationControl => new RotationControlActions(this);
    private int m_KeyboardAndMouseSchemeIndex = -1;
    public InputControlScheme KeyboardAndMouseScheme
    {
        get
        {
            if (m_KeyboardAndMouseSchemeIndex == -1) m_KeyboardAndMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard And Mouse");
            return asset.controlSchemes[m_KeyboardAndMouseSchemeIndex];
        }
    }
    private int m_GampadSchemeIndex = -1;
    public InputControlScheme GampadScheme
    {
        get
        {
            if (m_GampadSchemeIndex == -1) m_GampadSchemeIndex = asset.FindControlSchemeIndex("Gampad");
            return asset.controlSchemes[m_GampadSchemeIndex];
        }
    }
    public interface IRotationControlActions
    {
        void OnRotate(InputAction.CallbackContext context);
    }
}
